apiVersion: v1
kind: Service
metadata:
  name: developer
  labels:
    app: developer
    service: developer
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: developer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devhub-developer
  labels:
    account: developer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer-v1
  labels:
    app: developer
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: developer
      version: v1
  template:
    metadata:
      labels:
        app: developer
        version: v1
    spec:
      serviceAccountName: devhub-developer
      containers:
        - name: developer
          image: steven8519/developer
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
# Mongo host path rc
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
        - image: mongo
          name: mongo
          ports:
            - name: mongo
              containerPort: 27017
              hostPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          hostPath:
            path: /tmp/dbbackup
---
# Mongo Node Port RC
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo